export const testQuestions = {
  inputQuestion1: {
    body: 'questionBody1',
    correctAnswers: [
      'correct answer for question1',
      'answer1',
      'universal correct answer',
    ],
  },
  outputQuestion1Sa: {
    id: expect.any(String),
    body: 'questionBody1',
    correctAnswers: [
      'correct answer for question1',
      'answer1',
      'universal correct answer',
    ],
    published: false,
    createdAt: expect.any(String),
    updatedAt: null,
  },
  updateQuestion1: {
    body: 'updatedQuestion1',
    correctAnswers: [
      'updated correct answer for question1',
      'updatedAnswer1',
      'universal correct answer',
    ],
  },
  updatedOutputQuestion1Sa: {
    id: expect.any(String),
    body: 'updatedQuestion1',
    correctAnswers: [
      'updated correct answer for question1',
      'updatedAnswer1',
      'universal correct answer',
    ],
    published: false,
    createdAt: expect.any(String),
    updatedAt: expect.any(String),
  },
  updatedPublishedOutputQuestion1Sa: {
    id: expect.any(String),
    body: 'updatedQuestion1',
    correctAnswers: [
      'updated correct answer for question1',
      'updatedAnswer1',
      'universal correct answer',
    ],
    published: true,
    createdAt: expect.any(String),
    updatedAt: expect.any(String),
  },
  outputPublishedQuestion1Sa: {
    id: expect.any(String),
    body: 'questionBody1',
    correctAnswers: [
      'correct answer for question1',
      'answer1',
      'universal correct answer',
    ],
    published: true,
    createdAt: expect.any(String),
    updatedAt: expect.any(String),
  },
  inputQuestion2: {
    body: 'questionBody2',
    correctAnswers: [
      'correct answer for question2',
      'answer2',
      'universal correct answer',
    ],
  },
  outputQuestion2Sa: {
    id: expect.any(String),
    body: 'questionBody2',
    correctAnswers: [
      'correct answer for question2',
      'answer2',
      'universal correct answer',
    ],
    published: false,
    createdAt: expect.any(String),
    updatedAt: null,
  },
  outputPublishedQuestion2Sa: {
    id: expect.any(String),
    body: 'questionBody2',
    correctAnswers: [
      'correct answer for question2',
      'answer2',
      'universal correct answer',
    ],
    published: true,
    createdAt: expect.any(String),
    updatedAt: expect.any(String),
  },
  inputQuestion3: {
    body: 'questionBody3',
    correctAnswers: [
      'correct answer for question3',
      'answer3',
      'universal correct answer',
    ],
  },
  outputQuestion3Sa: {
    id: expect.any(String),
    body: 'questionBody3',
    correctAnswers: [
      'correct answer for question3',
      'answer3',
      'universal correct answer',
    ],
    published: false,
    createdAt: expect.any(String),
    updatedAt: null,
  },
  outputPublishedQuestion3Sa: {
    id: expect.any(String),
    body: 'questionBody3',
    correctAnswers: [
      'correct answer for question3',
      'answer3',
      'universal correct answer',
    ],
    published: true,
    createdAt: expect.any(String),
    updatedAt: expect.any(String),
  },
  inputQuestion4: {
    body: 'questionBody4',
    correctAnswers: [
      'correct answer for question4',
      'answer4',
      'universal correct answer',
    ],
  },
  outputQuestion4Sa: {
    id: expect.any(String),
    body: 'questionBody4',
    correctAnswers: [
      'correct answer for question4',
      'answer4',
      'universal correct answer',
    ],
    published: false,
    createdAt: expect.any(String),
    updatedAt: null,
  },
  outputPublishedQuestion4Sa: {
    id: expect.any(String),
    body: 'questionBody4',
    correctAnswers: [
      'correct answer for question4',
      'answer4',
      'universal correct answer',
    ],
    published: true,
    createdAt: expect.any(String),
    updatedAt: expect.any(String),
  },
  inputQuestion5: {
    body: 'questionBody5',
    correctAnswers: [
      'correct answer for question5',
      'answer5',
      'universal correct answer',
    ],
  },
  outputQuestion5Sa: {
    id: expect.any(String),
    body: 'questionBody5',
    correctAnswers: [
      'correct answer for question5',
      'answer5',
      'universal correct answer',
    ],
    published: false,
    createdAt: expect.any(String),
    updatedAt: null,
  },
  outputPublishedQuestion5Sa: {
    id: expect.any(String),
    body: 'questionBody5',
    correctAnswers: [
      'correct answer for question5',
      'answer5',
      'universal correct answer',
    ],
    published: true,
    createdAt: expect.any(String),
    updatedAt: expect.any(String),
  },
  inputQuestion6: {
    body: 'questionBody6',
    correctAnswers: [
      'correct answer for question6',
      'answer6',
      'universal correct answer',
    ],
  },
  outputQuestion6Sa: {
    id: expect.any(String),
    body: 'questionBody6',
    correctAnswers: [
      'correct answer for question6',
      'answer6',
      'universal correct answer',
    ],
    published: false,
    createdAt: expect.any(String),
    updatedAt: null,
  },
  outputPublishedQuestion6Sa: {
    id: expect.any(String),
    body: 'questionBody6',
    correctAnswers: [
      'correct answer for question6',
      'answer6',
      'universal correct answer',
    ],
    published: true,
    createdAt: expect.any(String),
    updatedAt: expect.any(String),
  },
  inputQuestion7: {
    body: 'questionBody7',
    correctAnswers: [
      'correct answer for question7',
      'answer7',
      'universal correct answer',
    ],
  },
  outputQuestion7Sa: {
    id: expect.any(String),
    body: 'questionBody7',
    correctAnswers: [
      'correct answer for question7',
      'answer7',
      'universal correct answer',
    ],
    published: false,
    createdAt: expect.any(String),
    updatedAt: null,
  },
  outputPublishedQuestion7Sa: {
    id: expect.any(String),
    body: 'questionBody7',
    correctAnswers: [
      'correct answer for question7',
      'answer7',
      'universal correct answer',
    ],
    published: true,
    createdAt: expect.any(String),
    updatedAt: expect.any(String),
  },
  inputQuestion8: {
    body: 'questionBody8',
    correctAnswers: [
      'correct answer for question8',
      'answer8',
      'universal correct answer',
    ],
  },
  outputQuestion8Sa: {
    id: expect.any(String),
    body: 'questionBody8',
    correctAnswers: [
      'correct answer for question8',
      'answer8',
      'universal correct answer',
    ],
    published: false,
    createdAt: expect.any(String),
    updatedAt: null,
  },
  outputPublishedQuestion8Sa: {
    id: expect.any(String),
    body: 'questionBody8',
    correctAnswers: [
      'correct answer for question8',
      'answer8',
      'universal correct answer',
    ],
    published: true,
    createdAt: expect.any(String),
    updatedAt: expect.any(String),
  },
  inputQuestion9: {
    body: 'questionBody9',
    correctAnswers: [
      'correct answer for question9',
      'answer9',
      'universal correct answer',
    ],
  },
  outputQuestion9Sa: {
    id: expect.any(String),
    body: 'questionBody9',
    correctAnswers: [
      'correct answer for question9',
      'answer9',
      'universal correct answer',
    ],
    published: false,
    createdAt: expect.any(String),
    updatedAt: null,
  },
  outputPublishedQuestion9Sa: {
    id: expect.any(String),
    body: 'questionBody9',
    correctAnswers: [
      'correct answer for question9',
      'answer9',
      'universal correct answer',
    ],
    published: true,
    createdAt: expect.any(String),
    updatedAt: expect.any(String),
  },
  inputQuestion10: {
    body: 'questionBody10',
    correctAnswers: [
      'correct answer for question10',
      'answer10',
      'universal correct answer',
    ],
  },
  outputQuestion10Sa: {
    id: expect.any(String),
    body: 'questionBody10',
    correctAnswers: [
      'correct answer for question10',
      'answer10',
      'universal correct answer',
    ],
    published: false,
    createdAt: expect.any(String),
    updatedAt: null,
  },
  outputPublishedQuestion10Sa: {
    id: expect.any(String),
    body: 'questionBody10',
    correctAnswers: [
      'correct answer for question10',
      'answer10',
      'universal correct answer',
    ],
    published: true,
    createdAt: expect.any(String),
    updatedAt: expect.any(String),
  },
};
